/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 --shadows .\public\models\ground.glb 
*/

import { useGLTF } from "@react-three/drei";

export function Ground(props) {
  const { nodes, materials } = useGLTF("./models/ground.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.terrain.geometry}
        material={materials.terrain_floor}
      />
    </group>
  );
}

useGLTF.preload("./models/ground.glb");
