/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 -k -K --shadows -M .\\public\\models\\ground.glb 
*/

// import React, { useRef } from "react";
import { useEffect, useRef } from "react";
import { useNavMesh } from "@ssethsara/react-three-npc";

export function NavMeshConvex(props) {
  const ref = useRef();
  const level = useNavMesh((state) => state.level);

  // Register ref with store
  useEffect(() => {
    if (ref.current) {
      useNavMesh.setState((state) => ({
        refs: {
          ...state.refs,
          level: level,
        },
      }));
    }
  }, []);

  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.5, 0]}>
        <mesh material={level.material} geometry={level.geometry} />
      </group>
    </group>
  );
}
